TNA/Controllers/TrainingLeadController.cs
using BAL.Repository;
using DAL.DBEntities;
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using TNA_ViewModel.Model;
using TNAApp_ViewModel.Model;
using static TNA_ViewModel.Model.TNA_VM;

namespace TNA.Controllers
{
    public class TrainingLeadController : BaseController
    {
        TrainingLeadRepository TrainingLeadRepo;

        public TrainingLeadController()
        {
            TrainingLeadRepo = new TrainingLeadRepository(new vt_TNAEntity());
        }

        #region Dashboard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult getTraining()
        {
            try
            {
                var dataList = TrainingLeadRepo.getTraining();

                if (dataList != null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult TrainingCalendar()
        {
            return View();
        }
        public ActionResult getTrainingCalendar()
        {

            System.Data.DataTable dt = new System.Data.DataTable();

            try
            {
                var TrainerID = Convert.ToInt32(CurrentUser.User.ID);
                dt = TrainingLeadRepo.GetDataforTrainingCalendar();
                var data = JsonConvert.SerializeObject(dt);
                if (dt != null)
                {
                    return Json(new { Status = true, Message = "Data found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, DataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult GetCounterValue()
        {
            try
            {
                var result = TrainingLeadRepo.GetCounterValue();
                if (result.Rows.Count > 0)
                {
                    var data = JsonConvert.SerializeObject(result);
                    return Json(new { Status = true, Message = "Record found.", data = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Null", data = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = "Record not found.", data = "" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CurrentMonthTraining()
        {
            try
            {
                var dataList = TrainingLeadRepo.CurrentMonthTraining();

                if (dataList != null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult CurrentMonthSession()
        {
            try
            {
                var dataList = TrainingLeadRepo.CurrentMonthSession();

                if (dataList != null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }
       
        #endregion

        #region Add TNA Page
        public ActionResult AddTNA()
        {
            return View(new TNAForm());
        }

        public JsonResult GetAllTrainings()
        {
            //List<TNA_Trainings> TrainingList = new List<TNA_Trainings>();
           // List<vt_Trainings> TrainingList = new List<vt_Trainings>();
            try
            {
               var TrainingList = TrainingLeadRepo.GetAllActiveTrainings();
                var JSON_TrainingList = JsonConvert.SerializeObject(TrainingList);
                //TrainingList = TrainingLeadRepo.GetAllTrainingsWithDepart();

                if (TrainingList != null)
                {
                    return Json(new { Status = true, Message = "Trainings found.", Trainings = JSON_TrainingList }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                   
                    return Json(new { Status = false, Message = "No trainings found.", Trainings = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                
                return Json(new { Status = false, Message = ex.Message, Trainings = "" }, JsonRequestBehavior.AllowGet);
            }
        }

        //public JsonResult GetAllTrainings_Edit(int ID)
        //{
        //    List<TNA_Trainings> ActiveTrainingList = new List<TNA_Trainings>();
        //    List<TNA_Trainings> SavedTrainingList = new List<TNA_Trainings>(); 
        //    List<TNA_Trainings> FinalDataSource = new List<TNA_Trainings>();

        //    try
        //    {
        //        //TrainingList = TrainingLeadRepo.GetAllTrainings();

        //        ActiveTrainingList = TrainingLeadRepo.GetAllTrainingsWithDepart();
        //        SavedTrainingList = TrainingLeadRepo.GetAllTrainingsWithDeparts_Saved(Convert.ToInt32(ID));

        //        foreach (var activetraining in ActiveTrainingList)
        //        {
        //            foreach (var savedtraining in SavedTrainingList)
        //            {
        //                if (activetraining.TrainingID == savedtraining.TrainingID)
        //                {
        //                    //Make Training Selected
        //                    activetraining.Training_IsSelected = savedtraining.Training_IsSelected;

        //                    if (activetraining.Departs.Count > 0)
        //                    {
        //                        foreach (var activedepart in activetraining.Departs)
        //                        {
        //                            foreach (var savedepart in savedtraining.Departs)
        //                            {
        //                                if (activedepart.DepartmentID == savedepart.DepartmentID)
        //                                {
        //                                    activedepart.Department_IsLocked = savedepart.Department_IsLocked;
        //                                }
        //                            }
        //                        }
        //                    }

        //                }
        //            }
        //        }

        //        FinalDataSource = ActiveTrainingList;

        //        if (FinalDataSource != null)
        //        {
        //            return Json(new { Status = true, Message = "Trainings Found.", Trainings = FinalDataSource }, JsonRequestBehavior.AllowGet);
        //        }
        //        else
        //        {
        //            FinalDataSource = null;
        //            return Json(new { Status = false, Message = "No Trainings Found.", Trainings = FinalDataSource }, JsonRequestBehavior.AllowGet);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        FinalDataSource = null;
        //        return Json(new { Status = false, Message = ex.Message, Trainings = FinalDataSource }, JsonRequestBehavior.AllowGet);
        //    }
        //}

        //public JsonResult GetDepartmentByTrainingID(int ID)
        //{
        //    List<GetTrainingDepartList> DepartList = new List<GetTrainingDepartList>();
        //    try
        //    {
        //        DepartList = TrainingLeadRepo.GetDepartsByTrainingID(Convert.ToInt32(ID));

        //        if (DepartList != null)
        //        {
        //            return Json(new { Status = true, Message = "Departments Found.", DataList = DepartList }, JsonRequestBehavior.AllowGet);
        //        }
        //        else
        //        {
        //            DepartList = null;
        //            return Json(new { Status = false, Message = "No Departments Found.", DataList = DepartList }, JsonRequestBehavior.AllowGet);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        DepartList = null;

TNA/Views/TrainingLead/ActiveTrainings.cshtml
@{
    ViewBag.Title = "ActiveTrainings";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var this_controller = (TNA.Controllers.BaseController)ViewContext.Controller;
    var _current_user = this_controller.CurrentUser;
    
}
<input type="hidden" id="tna_prefix" name="tna_prefix" value="@TNAApp_ViewModel.Model.vt_Common.GetPathPrefix()" /> <!-- Hidden Field for Prefix-->
<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">
                    <ul class="breadcrumb">
                        @{

                            if (_current_user.User.RoleID == 2)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "TrainingLead")">Dashboard</a></li>
                                <li class="breadcrumb-item active">TNA's List</li>
                            }
                            else if (_current_user.User.RoleID == 1)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Admin")">Dashboard</a></li>
                                <li class="breadcrumb-item active">TNA's List</li>
                            }
                        }
                       
                    </ul>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card min-height-70vh">
                    <div class="header">
                        <h2>TNA's List<small></small> </h2>
                        @*<button type="button" id="btnTraining" onclick="location.href='@Url.Action("AddTNA","TrainingLead")'" class="btn  btn-raised bg-red  waves-effect Header_Right_Btn">CREATE TNA</button>*@
                    </div>
                    <div class="body">
                        <div id="TNAsGrid"></div>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    @*<div class="header">
                        <h2> TNA Records <small></small> </h2>
                        <button type="button" id="btnTraining" onclick="location.href='@Url.Action("AddTNA","TrainingLead")'" class="btn  btn-raised bg-red  waves-effect Header_Right_Btn">CREATE TNA</button>
                    </div>*@
        @*<div id="TNAsGrid"></div>
                    </div>
                </div>
            </div>*@

    </div>
</section>

<!-- Small Size -->
@*<div class="modal fade" id="DeleteTNA" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="smallModalLabel">Delete TNA</h4>
                </div>
                <div class="modal-body">
                    Are you sure to delete <b>"TNA"</b> ?.
                </div>
                <div class="modal-footer">
                    <button tnaid="" type="button" class="btnDelete btn btn-link waves-effect">Yes</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>*@

<script>

    $(document).ready(function () {
        BindTNAsGrid();
    });


    function BindTNAsGrid() {
        $.ajax({
            url: '@Url.Action("ActiveTnaTrainings", "TrainingLead")',
            //url: "/" + $('#tna_prefix').val() + "/TrainingLead/ActiveTnaTrainings",
            contentType: 'application/json; charset=utf-8',
            type: 'GET',
            dataType: 'json',
            data: {},
            success: function (response) {
                debugger

                //if (response.Status)
                //{
                $("#TNAsGrid").dxDataGrid({
                    dataSource: response.TNAs,
                    columnsAutoWidth: true,
                    showBorders: true,
                    showColumnHeaders: true,
                    paging: {
                        pageSize: 10
                    },
                    filterRow: {
                        visible: true,
                        applyFilter: "auto"
                    },
                    headerFilter: {
                        visible: true
                    },

                    columns: [
                        {
                            dataField: "TNAName",
                            caption: "TNA Name",
                            alignment: "center",
                            //width: "auto",
                        },
                        {
                            dataField: "TrainingName",
                            caption: "Training Name",
                            alignment: "center",
                            //width: "auto",
                        },
                        {
                            dataField: "Descriptions",
                            caption: "Descriptions",
                            alignment: "center",
                            //width: "auto",
                        },
                        {
                            dataField: "Days",
                            caption: "Days",
                            alignment: "center",
                            //width: "auto",
                        },
                        {
                            dataField: "ID",
                            caption: "Action",
                            alignment: "center",
                            width: "auto",
                            allowHeaderFiltering: false,
                            allowFiltering: false,
                            cellTemplate: function (container, options) {
                                //trainingid = options.value;
                                trainingID = options.data.TrainingID;
                                tnaID = options.data.TNAID;
                                var IDs = trainingID + "^" + tnaID;

                                if ($('#tna_prefix').val() == "") {
                                    url = "/TrainingLead/AssignSessionUsers/" + IDs + "";
                                }
                                else {
                                    url = "/" + $('#tna_prefix').val() + "/TrainingLead/AssignSessionUsers/" + IDs + "";
                                }

                                $("<div>")
                                    .append($("<a class='TNAEdit' href='" + url + "' _id=" + IDs + " title='View Nominees for Training'><i class='fa fa-users'></i></a>"))
                                    //.append($("<a class='TNADelete' _id=" + options.value + " title='Delete'><i class='material-icons actions_icons_delete'>delete</i></a>"))
                                    .appendTo(container);
                            }
                        }
                    ]
                });
                //}

            },
            error: function (xhr) {
                debugger
            }
        });
    }


    @*$('body').on('click', '.TNADelete', function () {

        $('.btnDelete').attr("tnaid", $(this).attr('_id'));
        $("#DeleteTNA").modal("show");

    });


    $(".btnDelete").click(function () {

        var tnaID = $(this).attr('tnaid');

        $.ajax({
            url: '@Url.Action("DeleteTNA", "TrainingLead")',
            type: "GET",
            data: {
                ID: tnaID
            },
            success: function (response) {
                debugger
                if (response.Status) {
                    AlertToast('success', response.Message);
                    BindTNAsGrid();
                    $("#DeleteTNA").modal("hide");
                }
                else {
                    AlertToast('error', response.Message);
                }

            },
            error: function (xhr) {
                debugger
            }
        });
    });*@

</script>

TNA/Views/TrainingLead/ClosedSessionDetail.cshtml
@model TNA_ViewModel.Model.TNA_VM.ActiveTrainingsSessions_mdl
@{
    ViewBag.Title = "ClosedSessionDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var this_controller = (TNA.Controllers.BaseController)ViewContext.Controller;
    var _current_user = this_controller.CurrentUser;
}

<input type="hidden"  name="sessionid" id="sessionid" value="@Model.SessionID" />
<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">
                    <ul class="breadcrumb">
                        @{

                            if (_current_user.User.RoleID == 2)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "TrainingLead")">Dashboard</a></li>
                                <li class="breadcrumb-item active">Closed Sessions Detail</li>
                            }
                            else if (_current_user.User.RoleID == 1)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Admin")">Dashboard</a></li>
                                <li class="breadcrumb-item active">Closed Sessions Detail</li>
                            }
                        }
                      
                    </ul>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card min-height-70vh">
                    <div class="header">
                        <h2> Closed Session Detail  <small></small> </h2>

                    </div>



                    <div class="body">
                        <div class="row dragDrop_row">
                            <div class="col-md-12">
                                <div class="" id="div-main-TNA-Details">
                                                          

                                  

                                </div>
                            </div>
                        </div>

                        <div id="buttonDP" class="text-right mb-10">
                            <button type="button" id="btnDownload" class="btnPublish btn btn-raised bg-red  waves-effect tna_purpl_btn"><i class="far fa-file-pdf"></i> Download</button> 
                            <button id="btnPrint" class="btn btn-raised btn_light waves-effect"><i class="fas fa-print"></i> Print</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</section>
<script src="~/Scripts/print.min.js"></script>
<script>
    $(document).ready(function () {
        $('#buttonDP').css({"display":"none"});
      
        LoadSessionDetail();
    });
   
    var jsondata=[];
    var userdata=[];
    var objt = {};
    

    function LoadSessionDetail() {
        var _sessionID = $('#sessionid').val();
        $.ajax({
            url: '@Url.Action("GetDetailofSessionbyID", "TrainingLead")',
            type: 'POST',
            data: { SessionID: _sessionID },
            success: function (response) {
                debugger
                 jsondata = JSON.parse(response);
            objt = {
                    TNAID:jsondata[0].TNAID,
                    TrainingID : jsondata[0].TrainingID,
                    SessionId:jsondata[0].SessionID
                }

                userdata= LoadsessionUsers(objt);
                PopulatedataintoHTML(jsondata, userdata);
                if (jsondata.length>0) {
                    $('#buttonDP').css({ "display": "block" });
                }
            },
            error: function (response) {


            }

        });
    }

    function LoadsessionUsers(objt) {

        var responseData=[];
        $.ajax({
            url: '@Url.Action("GetUsersDetailofSession", "TrainingLead")',
            type: 'POST',
            async: false,
            data: objt,
            success: function (response) {
                debugger
                responseData = JSON.parse(response.data);

            },
            error: function (response) {
                responseData = null;

            }

        });

        return responseData;
    }

    function PopulatedataintoHTML(dataSource, userdata) {
        var html = '';
        html += '<div class="dragDrop_bx" >' +
                    '<p class="heading">Training Name :' + dataSource[0].TrainingName +
                        '<span style="float:right; font-weight:bold; margin-right:30px;" > Participants :' +
                            '<span class="participants-counts">' + userdata.length + '</span>' +
                        '</span>' +
                    '</p>' +
                    '<div class="div-container-trainingname">' +
                     '<p ><strong>TNA Name : </strong>' + dataSource[0].TNAName + '</p>' +
                      '<p ><strong>Trainer Name : </strong>' + dataSource[0].FullName + '</p>' +
                        '<p><strong>Training Descriptions : </strong>' + dataSource[0].Description + '</p>' +
                        '<p ><strong>Session Name : </strong>' + dataSource[0].SessionName + '</p>' +
                        '<p id="AllowedParticipants"><strong>Total Participants Allowed : </strong>' + dataSource[0].Participants + '</p>' +
                        '<p><strong>Session Start Date : </strong>' + dataSource[0].SessionStart + '  ' + dataSource[0].StartTime + '<br /><strong>Session End Date : </strong>' + dataSource[0].SessionEnd + '  ' + dataSource[0].EndTime + '</p>' +
                    '</div>' +
                    '<ul class="main_box cstm_ulbx" >' +

                        '<li id="li-dropUser">' +

                           '<div class="table-responsive">'+
                                        '<table id="userTable" class="table">'+
                                            '<tr>'+
                                                '<th>Employee Name</th>'+
                                                '<th>Department</th>' +
                                                '<th>Feedback</th>' +
                                                '<th>Attendance</th>' +
                                            '</tr>'+
                                        '</table>'+
                                    '</div>'+

                        '</li>' +
                    '</ul>' +
               '</div>';

        $('#div-main-TNA-Details').append(html);
       
        $.each(userdata, function (key, value) {

            if (value.Attendence) {

                $('#userTable').append('<tr><td>' + value.ReporteeName + '</td><td>' + value.DepartmentName + '</td><td>' + (value.Feedback!=null ? value.Feedback :" ")  + '</td><td><i class="fas fa-check"></i></td></tr>');
            }

            else {
                $('#userTable').append('<tr><td>' + value.ReporteeName + '</td><td>' + value.DepartmentName + '</td><td>' + (value.Feedback != null ? value.Feedback : " ") + '</td><td><i class="fas fa-times"></i></td></tr>');
            }
        });

      

    }


    function Download(){

        window.location.href = '@Url.Action("downloadInvoice","TrainingLead")?Ids=' + JSON.stringify(objt);
    }

    $('#btnDownload').on('click', function () {
        Download();
    });

    $('#btnPrint').on('click', function () {
        onPrintClick();
    });

    function onPrintClick() {
        $(".cstm_loader").css({
            "display": "block"
        });

        $.ajax({

            url: '@Url.Action("downloadInvoice","TrainingLead")?Ids=' + JSON.stringify(objt),
            method: "GET",            
            success: function (response) {
                printJS('/TNA/Content/Upload/SessionPDF.pdf');
                //printJS('/Content/Upload/SessionPDF.pdf');
                $(".cstm_loader").css({
                    "display": "none"
                });
            },
            error: function () {
                AlertToast("error", "Failed to load Print Screen.");
                $(".cstm_loader").css({
                    "display": "none"
                });
            }
        });

    }
</script>