TNA/Controllers/LineManagerController.cs
using TNA.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static TNA_ViewModel.Model.TNA_VM;
using BAL.Repository;
using DAL.DBEntities;
using System.Data;
using System.IO;
using TNAApp_ViewModel.Model;
using System.Data.SqlClient;
using Microsoft.Office.Interop.Excel;
using System.IO;
using Newtonsoft.Json;
using System.Collections;

namespace TNA.Controllers
{
    public class LineManagerController : BaseController
    {

        LineManagerRepository LineManagerRepo;
        public LineManagerController()
        {
            LineManagerRepo = new LineManagerRepository(new vt_TNAEntity());
        }

        public ActionResult ParticipantsInSession() {

            return View();
        }
        public ActionResult GetParticpantsInSessionList() {
            try
            {
            return Json(new {Success=true, data= JsonConvert.SerializeObject(LineManagerRepo.GetParticpantsInSessionList(Convert.ToInt32(CurrentUser.User.DepartmentID), Convert.ToInt32(CurrentUser.User.EmployeeID))) },JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
            }
          
        }

        [HttpPost]
        public ActionResult DeleteFromSessionandTraining(Remove_Participants_From_Session model)
        {
            try
            {
                model.LMID = Convert.ToInt32(CurrentUser.User.EmployeeID);
                model.DeptID = Convert.ToInt32(CurrentUser.User.DepartmentID);
                LineManagerRepo.DeleteFromSessionandTraining(model);
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
            }
            return View();
        }
        // GET: LineManager
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AssignUser()
        {
            List<GetDepartUsers> getListOfUsers = new List<GetDepartUsers>();
            try
            {
                var get_DepartmentID = CurrentUser.User.DepartmentID.ToString();
                var get_LoginID = Convert.ToInt32(CurrentUser.User.EmployeeID);
                var Location = Convert.ToString(CurrentUser.User.Location);
                var RoleID = Convert.ToInt32(CurrentUser.User.RoleID);
                getListOfUsers = LineManagerRepo.GetLineManagerUsersByLoginID(get_LoginID, get_DepartmentID,Location, RoleID);
                
                

                return View(getListOfUsers);
            }
            catch (Exception ex)
            {
                getListOfUsers = null;
                return View(getListOfUsers);
            }

                       
        }
        
        public JsonResult GetAllTrainingsCurrentUser()
        {
            List<GetAllTrainings_LM> lst_LM = new List<GetAllTrainings_LM>();
            try
            {
                //string departmentName = "CHC Team - North";
                lst_LM = LineManagerRepo.GetTrainingsCurrentUser
                    (
                    LineManagerRepo.GetDepartName_byDepartID(Convert.ToInt32(CurrentUser.User.DepartmentID)),
                    Convert.ToInt32(CurrentUser.User.DepartmentID),
                    Convert.ToInt32(CurrentUser.User.EmployeeID)
                    );
                return Json(new { lst_LM }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                lst_LM = null;
                return Json(new { lst_LM }, JsonRequestBehavior.AllowGet);
            }           
            
        }
        public JsonResult GetTNADeptWise()
        {
            try
            {
                int departID = Convert.ToInt32(CurrentUser.User.DepartmentID);
                var TNAList = LineManagerRepo.GetTNADeptWise(departID);
                if (TNAList.Rows.Count > 0)
                {
                    return Json(new { Status = true, Message = "Record found.", TNAList = JsonConvert.SerializeObject(TNAList) }, JsonRequestBehavior.AllowGet);
                }

                else
                {
                    return Json(new { Status = false, Message = "Record not found.", TNAList ="" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {

                return Json(new { Status = false, Message = ex.Message, TNAList = "" }, JsonRequestBehavior.AllowGet);
            }
            
           
        }

        //Search 
        public JsonResult GetSearchTrainings(string TNAName)
        {
            List<GetAllTrainings_LM> lst_LM = new List<GetAllTrainings_LM>();
            try
            {
               
                
                int departID = Convert.ToInt32(CurrentUser.User.DepartmentID);
                var departName = LineManagerRepo.GetDepartName_byDepartID(departID);
                //string departmentName = "CHC Team - North";
                lst_LM = LineManagerRepo.GetSearchTrainings(departName, TNAName);
                return Json(new { lst_LM }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                lst_LM = null;
                return Json(new { lst_LM }, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult InsertUsersToTraining(Add_or_Remove_Participants obj)
        {
            ResponseHeader Response = new ResponseHeader();
            try
            {
                var departID = Convert.ToInt32(CurrentUser.User.DepartmentID);
                obj.Department_Id = departID;
                obj.LM_ID = Convert.ToInt32(CurrentUser.User.EmployeeID);

                Response.Message = LineManagerRepo.InsertUserToTNATrainee(obj);
                Response.Status = true;
              

            }
            catch (Exception ex)
            {
                Response.Status = false;
                Response.Message = "During process unknown error occur. Please try again.";
            }
            return Json(Response, JsonRequestBehavior.AllowGet);
        }
        
        public JsonResult DeleteUserFromTnaTraining(TNATrainee_mdl obj)
        {
            ResponseHeader Response = new ResponseHeader();
            try
            {
                var departID = Convert.ToInt32(CurrentUser.User.DepartmentID);
                obj.DepartmentId = departID;
                //int userID = Convert.ToInt32(obj);
                var usersisexistinsess = LineManagerRepo.CheckUserisExistinSession(obj);
                if (usersisexistinsess.Rows.Count>0)
                {
                    if (usersisexistinsess == null || usersisexistinsess.Rows[0]["SessionID"] == DBNull.Value)
                    {
                        var DataInsertion = LineManagerRepo.DeleteUserTNATrainee(obj);
                        Response.Status = true;
                        Response.Message = "User Deleted Successfully.";
                    }

                    else
                    {
                        Response.Status = false;
                        Response.Message = "User could not be deleted because he/she assigned in session.";
                    }
                }

                else
                {
                    Response.Status = false;
                    Response.Message = "User could not be deleted because he/she assigned in session.";
                }





            }
            catch (Exception ex)
            {
                Response.Status = false;
                Response.Message = "There is some error please try again.";
            }
            return Json(Response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAssignUsersOnLoad(TNATrainee_mdl obj)
        {
            var departID = Convert.ToInt32(CurrentUser.User.DepartmentID);
            obj.EmpID = Convert.ToInt32(CurrentUser.User.EmployeeID);
            obj.DepartmentId = departID;
            obj.Location= Convert.ToString(CurrentUser.User.Location);
            obj.RoleID = Convert.ToInt32(CurrentUser.User.RoleID);
            var jsondata = LineManagerRepo.GetAssignUsersTrainingOnPageLoad(obj);
            if (jsondata.Rows.Count>0)
            {
                var getData = JsonConvert.SerializeObject(jsondata);
                return Json(new { getData }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                List<TNATrainee_mdl> list = new List<TNATrainee_mdl>();
                return Json(new { getData= list }, JsonRequestBehavior.AllowGet);
            }
            
                     
        }

        //Report
        public ActionResult ParticipantsWiseReport()
        {
            return View();
        }

        public ActionResult GetEmployeeList()
        {
            System.Data.DataTable getListOfUsers = new System.Data.DataTable();
            try
            {

                var get_DepartmentID = CurrentUser.User.DepartmentID.ToString();
                var get_LoginID = CurrentUser.User.EmployeeID.ToString();
                var roleID = Convert.ToInt32(CurrentUser.User.RoleID);
                var location = Convert.ToString(CurrentUser.User.Location);

                if (get_DepartmentID != null & get_LoginID != null)
                {
                   getListOfUsers = LineManagerRepo.GetUsersByLoginID(get_LoginID, get_DepartmentID,location, roleID);
                }
                if (getListOfUsers.Rows.Count > 0)
                {
                    var serializeobj = JsonConvert.SerializeObject(getListOfUsers);
                    return Json(new { Status = true, Message = "Success", data = serializeobj }, JsonRequestBehavior.AllowGet);
                }

TNA/Views/LineManager/AllClosedSession.cshtml
@{
    ViewBag.Title = "AllClosedSession";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("AllClosedSession", "LineManager")">Feedback</a></li>
                        @*<li class="breadcrumb-item active">Feedback</li>*@
                    </ul>
                </div>
            </div>
        </div>

       

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>Feedback<small></small> </h2>
                    </div>
                </div>
                <div class="body">
                    <div id="sessionGrid" class="cum_grid"></div>

                </div>
            </div>
        </div>
    </div>
    
</section>

<script>
    $(document).ready(function () {
        GetClosedSessionList();
        BindSessionGrid(null);
    });
    
    function GetClosedSessionList() {
        $.ajax({
            url: '@Url.Action("GetClosedSessionList", "LineManager")',
            type: 'GET',
            data: {},
            success: function (response) {
               debugger
                if (response.Status) {
                    BindSessionGrid(JSON.parse(response.data));
                }

                else {
                    var DataSource = [];
                    BindSessionGrid(DataSource);
                }

            },
            error: function () { }
        });
    };

    function BindSessionGrid(dataSource) {

        $("#sessionGrid").dxDataGrid({
            dataSource: dataSource,
            columnsAutoWidth: true,
            showBorders: true,
            showColumnHeaders: true,
            paging: {
                pageSize: 50
            },
            width: '100%',
            scrolling: {
                mode: "standard", // or "virtual" | "infinite"
            },
            //export: {
            //    enabled: true,
            //    fileName: "Participants Report"
            //},
            filterRow: {
                visible: true,
                applyFilter: "auto"
            },
            headerFilter: {
                visible: true
            },
            headerFilter: { visible: false, allowSearch: true },
            searchPanel: { visible: true },
            columnFixing: {enabled: true},
            columns: [
                {
                    dataField: "SessionID",
                    caption: "Action",
                    alignment: "center",
                    width: "auto",
                    fixed: true,
                    allowFiltering: false,
                     cellTemplate: function (container, info) {
                        debugger
                       $("<div>")
                              .append($("<a onclick='ViewParticipants(" + info.value + "," + info.data.TNAID + "," + info.data.TrainingID + ")' title='Detail View'><i class='fa fa-eye'></i></a>"))
                              .appendTo(container);
                   }
                },
                {
                    dataField: "TNAName",
                    caption: "TNA Name",
                    width: "150",
                    alignment: "left"
                },
                {
                    dataField: "TrainingName",
                    caption: "Training Name",
                    width: "150",
                    alignment: "left"
                },                 
                {
                    dataField: "SessionName",
                    caption: "Session Name",
                    alignment: "center",
                    width: "150",
                    alignment: "left"
                },
                {
                    dataField: "Participants",
                    caption: "No. of Participants",
                    alignment: "center",
                    width: "100",
                    alignment: "left"
                },
                {
                    dataField: "StartDate",
                    caption: "Start Date",
                    width: "150",
                    alignment: "left",
                    dataType: "date",
                    format: "dd/MM/yyyy",
                },
                {
                    dataField: "EndDate",
                    caption: "End Date",
                    width: "150",
                    alignment: "left",
                    dataType: "date",
                    format: "dd/MM/yyyy",
                },
                {
                    dataField: "FeedbackSubmitDate",
                    caption: "Feedback Submit Date",
                    width: "250",
                    alignment: "left",
                    dataType: "date",
                    format: "dd/MM/yyyy",
                },
                {
                    dataField: "StartTime",
                    caption: "Start Time",
                    width: "150",
                    alignment: "left",
                    
                },
                {
                    dataField: "EndTime",
                    caption: "End Time",
                    width: "150",
                    alignment: "left",
                    
                },
            ]
        });
    };


    function ViewParticipants(sessionID, TNAID, TrainingID) {
       
        window.location.href = "Participants?SessionID=" + sessionID + "&TNAID=" + TNAID + "&TrainingID=" + TrainingID;
       
    }
</script>

TNA/Views/LineManager/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<input type="hidden" id="tna_prefix" name="tna_prefix" value="@TNAApp_ViewModel.Model.vt_Common.GetPathPrefix()" /> <!-- Hidden Field for Prefix-->

TNA/Views/LineManager/ParticipantsInSession.cshtml
@{
    ViewBag.Title = "Participants In Session";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("ParticipantsInSession", "LineManager")">Participants in Session</a></li>
                       
                    </ul>
                </div>
            </div>
        </div>

       

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>Participants in Session<small></small> </h2>
                    </div>
                </div>
                <div class="body">
                    <div id="sessionGrid" class="cum_grid"></div>

                </div>
            </div>
        </div>
    </div>
    
</section>
<div class="modal fade" id="modal-Confirm-DeleteUser" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="smallModalLabel">Delete User</h4>
            </div>
            <div class="modal-body">
                Are you sure want to delete this <b>"USER"</b> ?
            </div>
            <div class="modal-footer">
                <button id="btn-DeleteUser" type="button" class="btnDelete btn btn-link waves-effect" onclick="DeleteFromSessionandTraining()">Yes</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>              
            </div>
        </div>
    </div>
</div>
<script>
    var dataDelete = {};
    $(document).ready(function () {
        GetParticpantsInSessionList();
    
    });

    function GetParticpantsInSessionList() {
        $.ajax({
            url: '@Url.Action("GetParticpantsInSessionList", "LineManager")',
            type: 'GET',
            data: {},
            success: function (response) {
               debugger
               if (response.Success) {

                    BindSessionGrid(JSON.parse(response.data));
                }

                else {
                    var DataSource = [];
                    BindSessionGrid(DataSource);
                }

            },
            error: function () { }
        });
    };

    function BindSessionGrid(dataSource) {

        $("#sessionGrid").dxDataGrid({
            dataSource: dataSource,
            columnAutoWidth: true,
            showBorders: true,
            showColumnHeaders: true,
            paging: {
                pageSize: 50
            },
            width: '100%',
            scrolling: {
                mode: "standard", // or "virtual" | "infinite"
            },
            //export: {
            //    enabled: true,
            //    fileName: "Participants Report"
            //},
            filterRow: {
                visible: true,
                applyFilter: "auto"
            },
            headerFilter: {
                visible: true
            },
            headerFilter: { visible: false, allowSearch: true },
            searchPanel: { visible: true },
            columnFixing: {enabled: true},
            columns: [
                {
                    dataField: "Session_ID",
                    caption: "Action",
                    alignment: "center",
                    fixed: true,
                    allowFiltering: false,
                     cellTemplate: function (container, info) {
                        debugger
                       $("<div>")
                              .append($("<a onclick='showDeleteModal(" + info.data.SP_ID + "," + info.value + "," + info.data.TNA_ID + "," + info.data.Training_ID + "," + info.data.ReporteeID + ")' title='Remove from session'><i class='fa fa-trash'></i></a>"))
                              .appendTo(container);
                   }
                },
                {
                    dataField: "ReporteeName",
                    caption: "Reportee Name",

                },
                 {
                     dataField: "SessionName",
                     caption: "Session Name",
                     alignment: "center",

                 },
                  {
                      dataField: "TNAName",
                      caption: "TNA Name"

                  },
                {
                    dataField: "TrainingName",
                    caption: "Training Name"

                },

                {
                    dataField: "StartDate",
                    caption: "Start Date",
                    dataType: "date",
                    format: "dd/MM/yyyy",
                },
                {
                    dataField: "EndDate",
                    caption: "End Date",
                    dataType: "date",
                    format: "dd/MM/yyyy",
                },
                {
                    dataField: "StartTime",
                    caption: "Start Time",

                },
                {
                    dataField: "EndTime",
                    caption: "End Time",

                },
            ]
        });
    };


    function showDeleteModal(SP_ID, Session_ID, TNA_ID, Training_ID, Reportee_ID) {
        dataDelete = {};

       $('#modal-Confirm-DeleteUser').modal('show');
       dataDelete = { SPID: SP_ID, SessionID: Session_ID, TNAID: TNA_ID, TrainingID: Training_ID, ReporteeID: Reportee_ID };


    }

    function DeleteFromSessionandTraining() {
      $.ajax({
            url: '@Url.Action("DeleteFromSessionandTraining", "LineManager")',
            type: 'Post',
            data: JSON.stringify(dataDelete),
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            success: function (result, status, xhr) {
                if (result.Success) {
                    AlertToast('success', "User deleted successfully.");
                }
                else {
                    AlertToast('error', "Some thing went wrong try again.");

                }
            },
            error: function (xhr, status, error) {
                AlertToast('error', "Some thing went wrong try again.");
            },
            complete: function (xhr, status) {
                $('#modal-Confirm-DeleteUser').modal('hide');
                GetParticpantsInSessionList();
            }

        });
    }
</script>

TNA/Views/LineManager/ParticipantsWiseReport.cshtml
@{
    ViewBag.Title = "ParticipantsWiseReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("AllClosedSession", "LineManager")">Feedback</a></li>
                        <li class="breadcrumb-item active">Participants Wise Report</li>
                    </ul>
                </div>
            </div>
        </div>
       
         <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>Participants Wise Report <small></small> </h2>
                      
                    </div>
                    <div class="container cstm-container">
                        <div class="row">
                            <div class="col-md-2">
                                <lable>Employee's List</lable>
                            </div>
                            <div class="col-md-5">
                                <div id="employeeList"></div>
                            </div>
                            <div class="col-md-2 sec-btn">
                                <button type="button" id="btnReport" class="btn  btn-raised bg-red  waves-effect Header_Right_Btn">Report</button>
                            </div>
                        </div>
                    </div>
                        
                        
                        
                    </div>
                    <div id="employeeReportGrid" class="cum_grid body"></div>                     


                </div>
            </div>
        </div>

        </div>
    </section>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js"></script>
<script>

    $(document).ready(function () {
        GetEmployeeList();
        BindReportGrid(null);
    });

    var dropDownEmpList;
    function GetEmployeeList(){
        $.ajax({
            url:'@Url.Action("GetEmployeeList", "LineManager")',
            type: 'GET',
            data: {},
            async:false,
            success: function (response) {
                if (response.Status) {
                    BindEmployeeDropDown(JSON.parse(response.data));
                }

                else {
                    var emptyDataSource = [];
                    BindEmployeeDropDown(emptyDataSource);
                }
                
            },
            error: function () { }
        });
    };

    function GetReportbyEmpID(EmpID){

        $.ajax({
            url: '@Url.Action("GetParticipantsWiseReport", "LineManager")',
            type: 'GET',
            data: {EmpID:EmpID},
            async: false,
            success: function (response) {
                if (response.Status) {

                    BindReportGrid(JSON.parse(response.data));
                    AlertToast('success', response.Message);
                }

                else {
                    BindReportGrid(null);
                    AlertToast('error', response.Message);
                }
            },
            error: function () { }
        });
    };

    function BindReportGrid(dataSource) {

        $("#employeeReportGrid").dxDataGrid({
            dataSource: dataSource,
            columnsAutoWidth: true,
            showBorders: true,
            showColumnHeaders: true,
            paging: {
                pageSize: 50
            },
            width: '100%',
            scrolling: {
                mode: "standard", // or "virtual" | "infinite"
            },
            export: {
                enabled: true,
                fileName: "Participants Report"
            },
            filterRow: {
                visible: true,
                applyFilter: "auto"
            },
            headerFilter: {
                visible: true
            },
            headerFilter: { visible: false, allowSearch: true },
            searchPanel: { visible: true },
            columns: [
                {
                    dataField: "TNAName",
                    caption: "TNA Name",
                    width: "150",
                    alignment: "left"
                },
                {
                    dataField: "TrainingName",
                    caption: "Training Name",
                    width: "150",
                    alignment: "left"
                },
                 {
                     dataField: "TopicName",
                     caption: "Topic Name",
                     width: "150",
                     alignment: "left"
                 },
                {
                    dataField: "SessionName",
                    caption: "Session Name",
                    alignment: "center",
                    width: "150",
                    alignment: "left"
                },
                {
                    dataField: "StartDate",
                    caption: "Start Date",
                    width: "250",
                    alignment: "left",
                    dataType: "date",
                    format:"dd/MM/yyyy",
                },
                 {
                     dataField: "EndDate",
                     caption: "EndDate",
                     alignment: "center",
                     width: "250",
                     dataType: "date",
                     alignment: "left",
                     format:"dd/MM/yyyy",
                 },
                {
                    dataField: "StartTime",
                    caption: "Start Time",
                    width: "150",
                    alignment: "left"
                },
                {
                    dataField: "EndTime",
                    caption: "End Time",
                    alignment: "center",
                    width: "150",
                    alignment: "left"
                },
                 {
                     dataField: "TrainerName",
                     caption: "Trainer Name",
                     alignment: "center",
                     width: "250",
                     alignment: "left",
                    
                 },
                   {
                       dataField: "TrainerFeedback",
                       caption: "Trainer Feedback",
                       alignment: "center",
                       width: "300",
                       alignment: "left",
                      
                   },
                   {
                       dataField: "Attendance",
                       caption: "Attendance",
                       alignment: "center",
                       width: "100",
                       alignment: "center",
                       dataType: "boolean"
                       
                   },
            ]
        });
    };

    function BindEmployeeDropDown(dataSource) {
        dropDownEmpList = $("#employeeList").dxSelectBox({
            dataSource: dataSource,
            placeholder: "Search / Select",
            displayExpr: "ReporteeName",
            valueExpr: "ReporteeID",
            searchEnabled: true,
        }).dxSelectBox("instance");
    }

    $('#btnReport').click(function () {
        GetReportbyEmpID(dropDownEmpList._options.value);
    });
</script>