TNA/Controllers/AdminController.cs
using TNA.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static TNA_ViewModel.Model.TNA_VM;
using BAL.Repository;
using DAL.DBEntities;
using System.Data;
using System.IO;
using TNAApp_ViewModel.Model;
using System.Data.SqlClient;
using Microsoft.Office.Interop.Excel;
using System.Configuration;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.SS.UserModel;

namespace TNA.Controllers
{
    public class AdminController : BaseController
    {
       
        AdminRepository AdminRepo;
        LoginRepository LoginRepo;
        public AdminController()
        {
            AdminRepo = new AdminRepository(new vt_TNAEntity());
            LoginRepo = new LoginRepository(new vt_TNAEntity());
        }

        #region Dashboard
        public ActionResult getTraining()
        {
            try
            {
                var dataList = AdminRepo.getTraining();
            
                if (dataList!=null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }
               
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList="" }, JsonRequestBehavior.AllowGet);
            }
            
        }

        public ActionResult TrainingCalendar()
        {
            return View();
        }
        public ActionResult getTrainingCalendar()
        {

            System.Data.DataTable dt = new System.Data.DataTable();

            try
            {
                var TrainerID = Convert.ToInt32(CurrentUser.User.ID);
                dt = AdminRepo.GetDataforTrainingCalendar();
                var data = JsonConvert.SerializeObject(dt);
                if (dt != null)
                {
                    return Json(new { Status = true, Message = "Data found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, DataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult GetCounterValue()
        {
            try
            {
                var result = AdminRepo.GetCounterValue();
                if (result.Rows.Count>0)
                {
                    var data = JsonConvert.SerializeObject(result);
                    return Json(new { Status = true, Message = "Record found.", data = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Null", data = "" }, JsonRequestBehavior.AllowGet);
                }
                
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = "Record not found.", data = "" }, JsonRequestBehavior.AllowGet);
            }
        }
        
        public ActionResult CurrentMonthTraining()
        {
            try
            {
                var dataList = AdminRepo.CurrentMonthTraining();

                if (dataList != null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult CurrentMonthSession()
        {
            try
            {
                var dataList = AdminRepo.CurrentMonthSession();

                if (dataList != null)
                {
                    var data = JsonConvert.SerializeObject(dataList);
                    return Json(new { Status = true, Message = "Data found.", dataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data not found.", dataList = "" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, dataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }
        #endregion

        public ActionResult GetLineManagers() {
            return View();
        }
        public ActionResult GetHeirarchy() {
            var Result = string.Empty;
            try
            {
                var dt = AdminRepo.GetHeirarchy();
                if (dt.Rows.Count>0)
                {
                    Result = JsonConvert.SerializeObject(dt);
                    return Json(new {data= Result, Status=true, Message="Record found." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    throw new Exception("Record not found.");
                }
            }
            catch (Exception ex)
            {

                return Json(new { data = Result, Status = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
     
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }


        #region Topic Page Functionality

        public ActionResult Topics()
        {
            return View();
        }

        public JsonResult GetAllDepartments()
        {
            var DepartList = AdminRepo.GetAllDeparts();

            return Json(new { DepartList }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult NewTopicForm()
        {
            //ViewBag.selectGroupList = new SelectList(GetAllGroupNames(), "GroupId", "Name");
            try
            {
                return PartialView("_TopicForm", new TopicForm());
            }
            catch (Exception ex)
            {
                return PartialView("_TopicForm", new TopicForm());
            }
        }


        public JsonResult GetAllTopics()
        {
            var TopicList = AdminRepo.GetAllTopics();

            return Json(TopicList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult AddTopic(TopicForm Header)
        {
            ResponseHeader Response = new ResponseHeader();

            try
            {

                if (ModelState.IsValid)
                {
                    if (Header.Departments == null)
                        throw new Exception("Select any one department against a topic.");

                    var Topic = AdminRepo.AddTopic(Header);
                    string ID = AdminRepo.GetLastTopicID();

                    TopicDepartments topicDeparts = new TopicDepartments();
                    topicDeparts.TopicID = Convert.ToInt32(ID);
                    topicDeparts.DepartmentID = Header.Departments;

                    if (topicDeparts.DepartmentID.Length > 0)
                    {


                        for (int i = 0; i < topicDeparts.DepartmentID.Length; i++)
                        {
                            System.Data.DataTable dtConversion = AdminRepo.AddNewTopicJunc(topicDeparts.TopicID, topicDeparts.DepartmentID[i]);

                        }
                    }

                    Response.Status = true;
                    Response.Message = "Topic added successfully.";

                    return Json(Response, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    throw new Exception("Please enter valid fields.");
                }
            }
            catch (Exception ex)
            {
                Response.Status = false;
                Response.Message = ex.Message;

                return Json(Response, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult EditTopic(int ID)
        {
            TopicForm Topic = new TopicForm();

            try
            {
                if (ID > 0)
                {
                    var vtTopic = AdminRepo.GetTopic_byID(ID);
                    if (vtTopic != null)
                    {
                        Topic = vtTopic;
                        var TopicDeparts = AdminRepo.GetTopicDeparts_byID(ID);
                        if (TopicDeparts != null)
                        {
                            Topic.Departments = TopicDeparts;
                            Topic.Status = true;
                            Topic.Message = "Topic load successfully.";
                        }
                        else
                        {
                            Topic.Departments = null;
                        }
                    }

                }
                else
                {
                    Topic.Status = false;
                    Topic.Message = "Topic not load successfully.";
                }


                return PartialView("_TopicForm", Topic);
            }
            catch (Exception ex)
            {
                Topic.Status = false;
                Topic.Message = ex.Message;

TNA/Controllers/CordinatorController.cs
using BAL.Repository;
using DAL.DBEntities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static TNA_ViewModel.Model.TNA_VM;

namespace TNA.Controllers
{
    public class CordinatorController : BaseController
    {


        TrainerRepository TrainerRepo;

        public CordinatorController()
        {
            TrainerRepo = new TrainerRepository(new vt_TNAEntity());
        }


        // GET: Trainer
        public ActionResult Index()
        {
            return View();
        }

        #region Session Assigned Users


        public ActionResult ConductedSessions()
        {
            return View();
        }

        public JsonResult GetAllSessions()
        {
            string jsonSessionList = string.Empty;

            try
            {
                var TrainerID = Convert.ToInt32(CurrentUser.User.ID);
                
                var SessionList = TrainerRepo.sp_GetAllSessions_Cordinator(TrainerID);

                if (SessionList.Rows.Count > 0)
                {
                    jsonSessionList = JsonConvert.SerializeObject(SessionList);

                    //return Json(jsonSessionList, JsonRequestBehavior.AllowGet);
                    return Json(new { Status = true, Message = "Sessions Found.", DataList = jsonSessionList }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    throw new Exception("Sessions Not Found.");
                }
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message , DataList = jsonSessionList }, JsonRequestBehavior.AllowGet);
            }
            
        }

        [HttpPost]
        public ActionResult SubmitAttendenceFeedback(List<AssignedUserGrid> Data)
        {
            ResponseHeader Response = new ResponseHeader();
            
            try
            {
                
                if (Data.Count > 0)
                {
                   // var Data = JsonConvert.DeserializeObject<List<AssignedUserGrid>>(UsersList);

                   
                        foreach (var item in Data)
                        {
                            var sessionUser = TrainerRepo.UpdateAttendence(item);
                        }

                        Response.Status = true;
                        Response.Message = "Attendance and Feedback Submitted Successfully.";

                        return Json(Response, JsonRequestBehavior.AllowGet);
                   
                }
                else
                {
                    throw new Exception("There are no records form submit.");
                }
                    

            }
            catch (Exception ex)
            {
                Response.Status = false;
                Response.Message = ex.Message;
                return Json(Response, JsonRequestBehavior.AllowGet);
                
            }
        }


        public JsonResult CloseSession()
        {
            try
            {
                var url_array = Request.UrlReferrer.ToString().Split('/');
                var sessionID = Convert.ToInt32(url_array.LastOrDefault());


                if (sessionID > 0)
                {
                    var dt = TrainerRepo.CloseSession_ByID(sessionID);

                    return Json(new { Status = true, Message = "Session Closed Successfully." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Session ID cannot be null." }, JsonRequestBehavior.AllowGet);
                }


            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }


        }

        [HttpGet]
        public ActionResult AssignedSessionUsers(int ID)
        {
            return View();
        }

        public JsonResult GetSessionAssignedUsers()
        {
            List<AssignedUserGrid> UserList = new List<AssignedUserGrid>();
            try
            {
                var url_array = Request.UrlReferrer.ToString().Split('/');
                var sessionID = Convert.ToInt32(url_array.LastOrDefault());

                UserList = TrainerRepo.GetAllSessionsAssignedUsers(sessionID);

                if (UserList != null)
                {
                    return Json(new { Status = true, Message = "Users Found.", DataList = UserList }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Users Not Found.", DataList = UserList }, JsonRequestBehavior.AllowGet);
                }


            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, DataList = UserList }, JsonRequestBehavior.AllowGet);
            }


        }
        #endregion

        public ActionResult TrainingCalendar()
        {
            return View();
        }
        public ActionResult getTrainingCalendar()
        {

            DataTable dt = new DataTable();
            
            try
            {
                var TrainerID = Convert.ToInt32(CurrentUser.User.ID);
                dt = TrainerRepo.getTrainingCalendar_Cordinator();
                var data = JsonConvert.SerializeObject(dt); 
                if (dt != null)
                {
                    return Json(new { Status = true, Message = "Data Found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Status = false, Message = "Data Not Found.", DataList = data }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, Message = ex.Message, DataList = "" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

TNA/Views/Cordinator/AssignedSessionUsers.cshtml
@{
    ViewBag.Title = "AssignedSessionUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var this_controller = (TNA.Controllers.BaseController)ViewContext.Controller;
    var _current_user = this_controller.CurrentUser;
}
<input type="hidden" id="tna_prefix" name="tna_prefix" value="@TNAApp_ViewModel.Model.vt_Common.GetPathPrefix()" /> <!-- Hidden Field for Prefix-->

<section class="content home">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-7">
                    <ul class="breadcrumb">
                        @{

                            if (_current_user.User.RoleID == 5)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("TrainingCalendar", "Cordinator")">Calendar</a></li>
                                <li class="breadcrumb-item active">Session Participants</li>
                            }
                            else if (_current_user.User.RoleID == 1)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Admin")">Dashboard</a></li>
                                <li class="breadcrumb-item active">Session Participants</li>
                            }

                            else if (_current_user.User.RoleID == 2)
                            {
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "TrainingLead")">Dashboard</a></li>
                                <li class="breadcrumb-item active">Session Participants</li>
                            }
                        }
                       
                    </ul>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h3></h3>
                        <h4></h4>
                        <h6 style="color:red"><marquee></marquee> </h6>
                    </div>

                    <div id="popupSessionForm"></div>  <!-- Dev-Extreme Topic Form Model-->

                    <div id="SessionsUsersGrid" class="cum_grid body"></div>
                    <div class="form-group">
                        <div class="row">
                           
                            <div class="col-9">
                                <button type="button" id="btnSubmit" class="input-group-text mb-3 tna_purpl_btn assign-setion-submit"><i class="far fa-paper-plane"></i>&nbsp; Submit</button>  @*Header_Right_Btn*@
                            </div>
                            
                            <div class="col-0">
                                <button id="btn_Closed" type="button" data-toggle="modal" data-target="#ClosedSession" data- class="input-group-text mb-3 tna_purpl_btn assign-setion-submit"><i class="fas fa-times-circle"></i>&nbsp; Close Session</button>
                            </div>
                        </div>
                        
                       
                    </div>
                   

                </div>
            </div>
        </div>

    </div>
</section>
<div class="modal fade tna_modal" id="ClosedSession" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="smallModalLabel">Closed Session</h4>
            </div>
            <div class="modal-body">
                Are you sure want to closed the Session ?.
            </div>
            <div class="modal-footer">
                <button id="btnClose" type="button" class="btn btn-link waves-effect" data-dismiss="modal"><i class="far fa-paper-plane"></i> Yes</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {

        GetSessionAssignedUsers();

    });

    
    function GetSessionAssignedUsers() {
        //debugger
        $.ajax({
            url: '@Url.Action("GetSessionAssignedUsers", "Cordinator")',
            //url: "/" + $('#tna_prefix').val() + "/Cordinator/GetSessionAssignedUsers",
            contentType: 'application/json; charset=utf-8',
            type: 'GET',
            dataType: 'json',
            data: {},
            success: function (response) {
                //debugger

                if (response.Status == true) {

                    //var sessionusersData = JSON.parse(response.DataList);
                    $(".header > h3").text(response.DataList[0].SessionName);
                    $(".header > h4").text("Total Participants: " + response.DataList.length);
                    BindGrid_SessionAssignedUsers(response.DataList);
                }
                else {
                    AlertToast('error', response.Message);
                    BindGrid_SessionAssignedUsers(null);

                }

            },
            error: function (xhr) {
                debugger
            }
        });
    }

    function BindGrid_SessionAssignedUsers(DataSource) {
        //debugger
        $("#SessionsUsersGrid").dxDataGrid({
            dataSource: DataSource,
            columnsAutoWidth: true,
            showBorders: true,
            showColumnHeaders: true,
            paging: {
                pageSize: 10
            },
            filterRow: {
                visible: true,
                applyFilter: "auto"
            },
            headerFilter: {
                visible: true
            },
            onCellPrepared: function (e) {
                debugger
                if (e.rowType == "data") {
                    if (e.data.SessionClosed) {
                        debugger
                        $("#SessionsUsersGrid").dxDataGrid("instance").option('editing.allowUpdating', false);
                        $("#btnSubmit").attr("disabled", "disabled");
                        $("#btn_Closed").attr("disabled", "disabled");
                        $(".header > h6 > marquee").text("Session is set to closed. You can't modify any thing.");
                    }
                    var today = new Date();
                    if (e.data.StartDate == null && e.data.EndDate==null) {
                        $("#SessionsUsersGrid").dxDataGrid("instance").option('editing.allowUpdating', false);
                        $("#btnSubmit").attr("disabled", "disabled");
                        $("#btn_Closed").attr("disabled", "disabled");
                        $(".header > h6 > marquee").text("You can't give attendance and feedback. Because session date time not set.");
                    }
                    else {
                        if (e.data.PublishEmail==false) {
                            $("#SessionsUsersGrid").dxDataGrid("instance").option('editing.allowUpdating', false);
                            $("#btnSubmit").attr("disabled", "disabled");
                            $("#btn_Closed").attr("disabled", "disabled");
                            $(".header > h6 > marquee").text("You can't give attendance and feedback. Because session publish email not sent to all participants.");
                        }

                        else {
                            if (moment(e.data.StartDate) > today || moment(e.data.EndDate) > today) {
                                $("#SessionsUsersGrid").dxDataGrid("instance").option('editing.allowUpdating', false);
                                $("#btnSubmit").attr("disabled", "disabled");
                                $("#btn_Closed").attr("disabled", "disabled");
                                $(".header > h6 > marquee").text("You can't give attendance and feedback. until when session to end.");
                            }
                        }
                       
                    }
                   
                }
            },
            editing: {
                mode: "cell",
                allowUpdating: true
            },
            columns: [
                {
                    dataField: "UserName",
                    caption: "Employee Name",
                    allowEditing: false,
                    //alignment: "center",
                    //width: "auto",
                },
                {
                    dataField: "Attendence",
                    caption: "Attendance",
                    dataType: "boolean"
                    //alignment: "center",
                    //width: "auto",
                },
                {
                    dataField: "Feedback",
                    caption: "Feedback",
                    //alignment: "center",
                    //width: "auto",
                    allowHeaderFiltering: false,
                    allowFiltering: false,
                }
            ]
        });
    }



    $("#btnSubmit").click(function () {
        debugger
        $("#SessionsUsersGrid").dxDataGrid("instance").saveEditData();
        var UsersList = $("#SessionsUsersGrid").dxDataGrid("instance").option("dataSource");

        if (UsersList != null)
        {
            if (UsersList.length > 0) {

                var dataList = JSON.stringify(UsersList);

                $.ajax({
                    url: '@Url.Action("SubmitAttendenceFeedback", "Cordinator")',
                    //url: "/" + $('#tna_prefix').val() + "/Cordinator/SubmitAttendenceFeedback",
                    contentType: 'application/json; charset=utf-8',
                    type: 'POST',
                    dataType: 'json',
                    data:  dataList,
                    success: function (response) {
                        debugger

                        if (response.Status == true) {

                            //var sessionusersData = JSON.parse(response.DataList);
                            AlertToast('success', response.Message);

                            GetSessionAssignedUsers();
                        }
                        else {
                            AlertToast('error', response.Message);


                        }

                    },
                    error: function (xhr) {
                        debugger
                    }
                });
            }
            else {
                AlertToast('error', 'There are no records for submit.');
            }
        }
    else
        {
            AlertToast('error', 'There are no records for submit.');
        }



    });


    $("#btnClose").click(function () {
        debugger
        var UsersList = $("#SessionsUsersGrid").dxDataGrid("instance").option("dataSource");
        if (UsersList != null)
        {
            $.ajax({
                url: '@Url.Action("CloseSession", "Cordinator")',
                //url: "/" + $('#tna_prefix').val() + "/Cordinator/SubmitAttendenceFeedback",
                //contentType: 'application/json; charset=utf-8',
                type: 'GET',

                success: function (response) {
                    debugger

                    if (response.Status == true) {

                        AlertToast('success', response.Message);
                        GetSessionAssignedUsers();
                    }
                    else {
                        AlertToast('error', response.Message);
                    }
                },
                error: function (xhr) {
                    debugger
                }
            });
        }

        else

        {
            AlertToast('error', 'Session can not closed because no users found.');
        }
    
    });

</script>

TNA/Views/Cordinator/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dashboard</h2>

<input type="hidden" id="tna_prefix" name="tna_prefix" value="@TNAApp_ViewModel.Model.vt_Common.GetPathPrefix()" /> <!-- Hidden Field for Prefix-->